import * as T from './vendor/three.module.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {mergeGeometries} from './vendor/BufferGeometryUtils.js';
import {racer,advance,lap,finish,ranking,activate,clamp,LAPS} from './core.mjs';
const $=id=>document.getElementById(id),TAU=Math.PI*2;
const courses=[{name:'Pilz-Promenade',tag:'SONNIG & SCHWUNGVOLL',icon:'✿',sky:0xa7dbe3,grass:0x7cba56,road:0x526574,points:[[0,62],[65,57],[105,15],[90,-47],[32,-72],[-21,-40],[-85,-61],[-108,-10],[-77,50]],seed:7},{name:'Sunset Valley',tag:'WEITE KURVEN',icon:'☀',sky:0xf1b393,grass:0xb2ae55,road:0x715e6c,points:[[0,70],[75,72],[108,26],[57,-8],[94,-70],[23,-94],[-32,-63],[-95,-74],[-113,-16],[-72,51]],seed:23},{name:'Sternen-Garten',tag:'TECHNISCH & KURVIG',icon:'✦',sky:0x586791,grass:0x4b846e,road:0x575b80,points:[[0,70],[74,52],[95,-3],[44,-28],[72,-73],[0,-86],[-43,-48],[-96,-58],[-99,15],[-49,42]],seed:41}];
const colors=[0xed6350,0xffc74a,0x55bdb2,0xa688dc],driverNames=['Ruby / Rot','Sunny / Gelb','Mint / Türkis','Nova / Violett'];
let selected=0,colorIndex=0,state='menu',elapsed=0,countdown=3,last=0,curve,length=1,boxes=[],racers=[],hazards=[],sparks=[],flags=[],frame=0,noticeTimer=0,course,engine,ctx,soundOn=true,beat=0,menuBeat=0,autoGas=false;
const coarseInput=matchMedia('(pointer:coarse)').matches,quality={level:0,dprCap:coarseInput?1.25:1.6,fpsFrames:0,fpsStart:0};
let renderer;try{renderer=new T.WebGLRenderer({canvas:$('game'),antialias:!coarseInput});}catch(e){$('error').hidden=false;$('error').textContent='Dein Browser benötigt WebGL für dieses 3D-Spiel. Bitte Hardwarebeschleunigung aktivieren und die Seite neu laden.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,quality.dprCap));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new T.Scene(),camera=new T.PerspectiveCamera(58,innerWidth/innerHeight,.1,800),world=new T.Group(),actors=new T.Group();scene.add(world,actors);const hemi=new T.HemisphereLight(0xffffff,0x587540,2);scene.add(hemi);const sun=new T.DirectionalLight(0xfff7db,3);sun.position.set(40,110,70);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-130,right:130,top:130,bottom:-130,far:350});sun.shadow.bias=-.0006;scene.add(sun);const fill=new T.DirectionalLight(0xbfd4ff,.45);fill.position.set(-60,40,-90);scene.add(fill);
// Sonnenglow als Sprite (billig, vom Nebel ausgenommen).
const sunTex=(()=>{const c=document.createElement('canvas');c.width=c.height=128;const q=c.getContext('2d');const g=q.createRadialGradient(64,64,6,64,64,64);g.addColorStop(0,'rgba(255,250,230,1)');g.addColorStop(.25,'rgba(255,244,200,.85)');g.addColorStop(1,'rgba(255,244,200,0)');q.fillStyle=g;q.fillRect(0,0,128,128);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;})();
const sunGlow=new T.Sprite(new T.SpriteMaterial({map:sunTex,transparent:true,depthWrite:false,fog:false}));sunGlow.scale.set(190,190,1);sunGlow.position.set(-320,240,-400);scene.add(sunGlow);
const mat=(color,extra={})=>new T.MeshStandardMaterial({color,roughness:.8,...extra});
// GLB-Prototypen aus Blender (MCP): Geometrien/Materialien werden geteilt und niemals disposet.
const sharedGeo=new Set(),sharedMat=new Set();let kartProto=null,pilzProto=null,gateProto=null,treeProto=null;
function markShared(root){root.traverse(o=>{if(o.isMesh){sharedGeo.add(o.geometry);for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m)sharedMat.add(m);}});}
function loadProto(url){return new Promise(resolve=>{new GLTFLoader().load(url,g=>{const merged=mergeByMaterial(g.scene);markShared(merged);resolve(merged);},undefined,()=>resolve(null));});}
// Meshes mit identischem Material zu einem Mesh verschmelzen: weniger Draw-Calls (Low-End/Mobile).
function mergeByMaterial(root){root.updateMatrixWorld(true);const groups=new Map();root.traverse(o=>{if(o.isMesh&&!Array.isArray(o.material)){const k=o.material.uuid;const e=groups.get(k)||{m:o.material,g:[]};e.g.push(o.geometry.clone().applyMatrix4(o.matrixWorld));groups.set(k,e);}});const out=new T.Group();for(const e of groups.values()){const geo=mergeGeometries(e.g,false);if(geo)out.add(new T.Mesh(geo,e.m));}return out;}
function cloneProto(proto){const c=proto.clone(true);c.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});return c;}
function applyTint(root,name,color){root.traverse(o=>{if(!o.isMesh)return;const fix=m=>{if(m&&m.name===name){const c=m.clone();c.color=new T.Color(color);return c;}return m;};o.material=Array.isArray(o.material)?o.material.map(fix):fix(o.material);});}
const cream=mat(0xffefd5),dark=mat(0x273943),tire=mat(0x25343b),white=mat(0xffffff),gold=mat(0xffdc64),green=mat(0x54aa55);
function mesh(geo,material,parent,x=0,y=0,z=0){const m=new T.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function sphere(parent,material,x,y,z,sx,sy=sx,sz=sx){const m=mesh(new T.SphereGeometry(1,14,10),material,parent,x,y,z);m.scale.set(sx,sy,sz);return m;}
function box(parent,material,x,y,z,a,b,c){return mesh(new T.BoxGeometry(a,b,c),material,parent,x,y,z);}
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
function sample(distance,offset=0){const u=((distance/length)%1+1)%1,p=curve.getPointAt(u),t=curve.getTangentAt(u).normalize();p.x+=t.z*offset;p.z-=t.x*offset;return {p,t,angle:Math.atan2(t.x,t.z)};}
function label(text,bg='#fff1d9',fg='#28523c',w=512,h=128){const c=document.createElement('canvas');c.width=w;c.height=h;const q=c.getContext('2d');q.fillStyle=bg;q.fillRect(0,0,w,h);q.fillStyle=fg;q.font=`900 ${Math.round(h*.52)}px Trebuchet MS`;q.textAlign='center';q.textBaseline='middle';q.fillText(text,w/2,h/2);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return new T.MeshBasicMaterial({map:tex,side:T.DoubleSide});}
// Billige Canvas-Texturen: Himmel-Verlauf und gesprenkelte Oberflaechen (Low-End-freundlich).
const hex=c=>'#'+c.getHexString();
function skyTexture(top,bottom){const c=document.createElement('canvas');c.width=2;c.height=256;const q=c.getContext('2d');const g=q.createLinearGradient(0,0,0,256);g.addColorStop(0,top);g.addColorStop(1,bottom);q.fillStyle=g;q.fillRect(0,0,2,256);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
function speckleTexture(base,spot,density=1200,size=256){const c=document.createElement('canvas');c.width=c.height=size;const q=c.getContext('2d');q.fillStyle=base;q.fillRect(0,0,size,size);for(let i=0;i<density;i++){q.globalAlpha=.1+Math.random()*.22;q.fillStyle=Math.random()<.5?spot:'#00000018';q.fillRect(Math.random()*size,Math.random()*size,2,2);}q.globalAlpha=1;const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;return t;}
function clearGroup(g){const persistent=new Set([cream,dark,tire,white,gold,green]),disposed=new Set();g.traverse(o=>{if(o.isMesh){if(o.geometry&&!sharedGeo.has(o.geometry))o.geometry?.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material])){if(m&&!persistent.has(m)&&!sharedMat.has(m)&&!disposed.has(m)){m.map?.dispose();m.dispose();disposed.add(m);}}}});g.clear();}
function roadStrip(offset,width,material,height=.04){const vertices=[],uv=[],indices=[],steps=640;for(let i=0;i<=steps;i++){for(const side of [-1,1]){const {p}=sample(i/steps*length,offset+side*width/2);vertices.push(p.x,height,p.z);uv.push(i/steps*100,side===-1?0:1);}if(i<steps){let a=i*2;indices.push(a,a+2,a+1,a+1,a+2,a+3);}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();const m=new T.Mesh(g,material);m.receiveShadow=true;world.add(m);}
function mushroom(x,z,s,color){if(pilzProto){const g=cloneProto(pilzProto);g.position.set(x,0,z);g.scale.setScalar(s);applyTint(g,'CapPaint',color);world.add(g);return g;}const g=new T.Group();g.position.set(x,0,z);g.scale.setScalar(s);world.add(g);mesh(new T.CylinderGeometry(.3,.52,2.5,12),cream,g,0,1.25,0);const cap=sphere(g,mat(color),0,2.65,0,1.6,.75,1.6);for(let j=0;j<7;j++){const a=j*2.4,r=j?1.04:0;const dot=sphere(g,white,Math.cos(a)*r,2.65+.75*Math.sqrt(1-(r/1.6)**2)+.04,Math.sin(a)*r,.27,.09,.27);dot.rotation.z=-Math.cos(a)*.35;dot.rotation.x=Math.sin(a)*.35;}return g;}
function tree(x,z,s,ci=0){if(treeProto){const g=cloneProto(treeProto);g.position.set(x,0,z);g.scale.setScalar(s);applyTint(g,'CapPaint',[0x4f9758,0x74b35b,0x5da04a][ci%3]);world.add(g);return g;}const g=new T.Group();g.position.set(x,0,z);g.scale.setScalar(s);world.add(g);mesh(new T.CylinderGeometry(.2,.4,2.7,7),mat(0x98714a),g,0,1.35,0);sphere(g,mat(0x4f9758),0,3.5,0,1.7,2.6,1.7);sphere(g,mat(0x74b35b),.55,4,.1,1.2,1.9,1.2);}
function kart(color){if(kartProto){const g=cloneProto(kartProto);applyTint(g,'BodyPaint',color);const shield=mesh(new T.SphereGeometry(1.65,20,14),new T.MeshBasicMaterial({color:0xffe263,transparent:true,opacity:.18,wireframe:true}),g,0,1,0);shield.visible=false;g.userData={wheels:[],shield};return g;}const g=new T.Group(),body=mat(color,{roughness:.35}),metal=mat(0xdce4da,{metalness:.3,roughness:.4});box(g,body,0,.68,0,1.75,.55,2.4);box(g,body,0,.62,1.2,1.5,.38,1.1);box(g,cream,0,.9,1.3,.55,.12,1);box(g,dark,0,.65,1.88,1.8,.18,.16);box(g,body,0,1,-1.3,2.1,.18,.38);box(g,dark,0,.95,-.28,.9,.75,.72);const wheels=[];for(const x of [-1,1])for(const z of [-.9,1]){const wheel=mesh(new T.CylinderGeometry(.43,.43,.38,14),tire,g,x,.44,z);wheel.rotation.z=Math.PI/2;wheels.push(wheel);const hub=mesh(new T.CylinderGeometry(.21,.21,.395,12),metal,g,x,.44,z);hub.rotation.z=Math.PI/2;}
 sphere(g,body,0,1.4,-.2,.49,.56,.43);sphere(g,cream,0,2.01,-.08,.45,.48,.43);sphere(g,body,0,2.27,-.12,.51,.26,.47);box(g,body,0,2.23,.34,.78,.07,.38);sphere(g,dark,-.16,2.02,.316,.055,.078,.035);sphere(g,dark,.16,2.02,.316,.055,.078,.035);sphere(g,cream,0,1.92,.4,.13,.1,.13);for(const x of [-.45,.45]){const hand=sphere(g,white,x,1.45,.51,.16);hand.scale.y=.16;}const steering=mesh(new T.TorusGeometry(.28,.055,6,12),dark,g,0,1.3,.65);steering.rotation.x=-.5;const shield=mesh(new T.SphereGeometry(1.65,20,14),new T.MeshBasicMaterial({color:0xffe263,transparent:true,opacity:.18,wireframe:true}),g,0,1,0);shield.visible=false;g.userData={wheels,shield};return g;}
function buildCourse(){clearGroup(world);clearGroup(actors);hazards=[];sparks=[];flags=[];course=courses[selected];const skyC=new T.Color(course.sky),horizonC=skyC.clone().lerp(new T.Color(course.grass),.42);scene.background=skyTexture(hex(skyC),hex(horizonC));scene.fog=new T.Fog(horizonC.getHex(),190,430);curve=new T.CatmullRomCurve3(course.points.map(([x,z])=>new T.Vector3(x,0,z)),true,'catmullrom',.38);curve.arcLengthDivisions=1800;length=curve.getLength();
 const grassC=new T.Color(course.grass),roadC=new T.Color(course.road);const ground=mesh(new T.CylinderGeometry(210,195,12,96),new T.MeshStandardMaterial({map:speckleTexture(hex(grassC),hex(grassC.clone().offsetHSL(0,-.05,.08)),2200),roughness:1}),world,0,-6.08,0);ground.receiveShadow=true;const sea=mesh(new T.PlaneGeometry(2500,2500),mat(selected===2?0x577da0:0x72c9cf,{roughness:.3}),world,0,-12,0);sea.rotation.x=-Math.PI/2;
 roadStrip(0,17.8,cream);roadStrip(0,15.2,new T.MeshStandardMaterial({map:speckleTexture(hex(roadC),hex(roadC.clone().offsetHSL(0,0,.07)),700),roughness:.9}),.065);
 for(let d=0;d<length;d+=5){for(const off of [-8.15,8.15]){const {p,angle}=sample(d,off);const b=box(world,Math.floor(d/5)%2?cream:mat(0xed745a),p.x,.1,p.z,.65,.15,4.8);b.rotation.y=angle;}if(Math.floor(d/5)%2===0){const {p,angle}=sample(d);const dash=box(world,cream,p.x,.07,p.z,.16,.025,2.5);dash.rotation.y=angle;}}
 const random=rng(course.seed),path=Array.from({length:170},(_,i)=>sample(i/170*length).p);
 for(let i=0;i<150;i++){const x=(random()-.5)*340,z=(random()-.5)*300;if(Math.hypot(x,z)>186||path.some(p=>Math.hypot(p.x-x,p.z-z)<14))continue;const s=1+random()*2.3;if(i%3===0)mushroom(x,z,s,[0xef7160,0xf1b35a,0xb292ce][i%3===0?i%9/3|0:0]);else tree(x,z,s*.8,i);}
 // Oversized landmarks visible over the track.
 mushroom(20,0,6.5,0xee6859);mushroom(40,7,3.4,0xf8b94e);mushroom(-40,-7,4,0x8d9ddb);
 for(let i=0;i<16;i++){const a=i/16*TAU,r=225+random()*70;const hill=sphere(world,mat(i%2?0x6c9c84:0x8daf8c),Math.cos(a)*r,-4,Math.sin(a)*r,25+random()*25,28+random()*34,24+random()*15);hill.castShadow=false;}
 for(let i=0;i<15;i++){const cloud=new T.Group();world.add(cloud);cloud.position.set((random()-.5)*420,45+random()*40,(random()-.5)*350);for(let k=0;k<4;k++){const puff=sphere(cloud,white,k*4-6,Math.sin(k)*2,0,5,3.5,3);puff.castShadow=false;}}
 // Start-Tor (GLB aus Blender) und Schachbrett; prozedurales Tor bleibt als Fallback.
 const start=sample(0),arch=new T.Group();arch.position.copy(start.p);arch.rotation.y=start.angle;world.add(arch);if(gateProto)arch.add(cloneProto(gateProto));else{box(arch,cream,-9,4,0,.6,8,.6);box(arch,cream,9,4,0,.6,8,.6);box(arch,mat(0xed6350),0,8,0,19,2,.7);}const bz=gateProto?.26:.37;mesh(new T.PlaneGeometry(16,1.6),label('MUSHROOM RALLY','#ed6350','#fff5d9'),arch,0,8,bz);const back=mesh(new T.PlaneGeometry(16,1.6),label('MUSHROOM RALLY','#ed6350','#fff5d9'),arch,0,8,-bz);back.rotation.y=Math.PI;for(let x=-7;x<8;x++)for(let z=0;z<3;z++)box(arch,(x+z)%2?dark:cream,x,.11,z-1,.95,.08,.95);
 for(const d of [length*.18,length*.43,length*.72]){const s=sample(d),g=new T.Group();g.position.copy(s.p);g.rotation.y=s.angle;world.add(g);for(let i=-3;i<=3;i++){const tile=box(g,mat(0xffd45c,{emissive:0xffa536,emissiveIntensity:.35}),i*1.8,.13,0,1.6,.12,4);box(g,cream,i*1.8,.21,-.4,.25,.025,1.8).rotation.y=.6;} }
 for(let i=1;i<course.points.length;i++){const s=sample(length*i/course.points.length,11),g=new T.Group();g.position.copy(s.p);g.rotation.y=s.angle;world.add(g);box(g,cream,0,1.4,0,.22,2.8,.22);mesh(new T.PlaneGeometry(3,1.6),label('› › ›','#ffe071','#284a3c'),g,0,3,0);}
 // Wehende Wimpel entlang der Strecke (Vertex-Animation, sehr guenstig).
 for(let i=0;i<14;i++){const s=sample(length*(i+.5)/14,i%2?9.6:-9.6),g=new T.Group();g.position.copy(s.p);g.rotation.y=s.angle;world.add(g);box(g,cream,0,1.55,0,.12,3.1,.12);const penn=mesh(new T.PlaneGeometry(1.5,.7,5,1),mat(i%2?0xed6350:0xffd45c,{side:T.DoubleSide}),g,.81,2.75,0);flags.push({mesh:penn,base:penn.geometry.attributes.position.array.slice()});}
 boxes=[];for(let j=0;j<6;j++)for(let k=-1;k<=1;k++){const d=length*(.09+j*.15),s=sample(d,k*4),g=new T.Group();g.position.copy(s.p);g.position.y=1.6;world.add(g);const cube=mesh(new T.BoxGeometry(1.5,1.5,1.5),[mat(0xffd858),mat(0xffd858),mat(0xffd858),mat(0xffd858),label('?','#ffcc4e','#fff9df',128,128),label('?','#ffcc4e','#fff9df',128,128)],g);g.userData.cube=cube;boxes.push({distance:d,offset:k*4,mesh:g,cooldown:0});}
 racers=Array.from({length:8},(_,i)=>racer(i,['Du','Peachy','Bramble','Pip','Luna','Mochi','Sunny','Nori'][i],i===0?colors[colorIndex]:[0xffb7c1,0x96b464,0xf7c055,0x918ed1,0x78c7d1,0xec9160,0x549a91][i-1]));racers.forEach(r=>{r.mesh=kart(r.color);actors.add(r.mesh);syncKart(r,0);});
 $('courseLabel').textContent=course.name;$('courseNo').textContent=String(selected+1).padStart(2,'0');drawMap();
}
function syncKart(r,dt){const {p,angle}=sample(r.distance,r.offset);r.mesh.position.copy(p);r.mesh.position.y=.1+Math.sin(elapsed*22+r.id)*.035*(r.speed/50);r.mesh.rotation.y=angle+(r.id===0&&r.drift>0?steering()*.3:0)+(r.stun>0?elapsed*14:0);r.mesh.rotation.z=r.id===0?-steering()*.065:0;r.mesh.userData.shield.visible=r.shield>0;}
const keys=new Set();function steering(){return (keys.has('ArrowLeft')||keys.has('KeyA')?1:0)-(keys.has('ArrowRight')||keys.has('KeyD')?1:0);}
function notice(text,duration=1.3){$('message').textContent=text;noticeTimer=duration;}
// Musik steht auf AN; Browser erlauben Ton erst ab der ersten Nutzereingabe -> hier armieren.
let audioReady=false;
function armAudio(){if(audioReady)return;audioReady=true;if(soundOn){audioInit();playBgm(state==='menu'||state==='finished'?'menu':'race');}}
addEventListener('pointerdown',armAudio,{once:true});addEventListener('keydown',armAudio,{once:true});
// Ansagen per lokaler Sprachausgabe (kein Netz, deutsch falls verfuegbar).
function say(text){if(!soundOn||!('speechSynthesis' in window))return;try{const u=new SpeechSynthesisUtterance(text);u.lang='de-DE';const v=speechSynthesis.getVoices().find(v=>v.lang&&v.lang.toLowerCase().startsWith('de'));if(v)u.voice=v;u.rate=1.1;u.pitch=1.05;u.volume=.9;speechSynthesis.cancel();speechSynthesis.speak(u);}catch{}}
if('speechSynthesis' in window)speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices();
function audioInit(){if(!ctx){ctx=new (window.AudioContext||window.webkitAudioContext)();engine=ctx.createOscillator();engine.type='sawtooth';const gain=ctx.createGain();gain.gain.value=.014;engine.connect(gain);gain.connect(ctx.destination);engine.start();engine.gain=gain;}ctx.resume().catch(()=>{});}
// BGM aus bereitgestellten MP3s (assets/audio) als <audio>-Loops; prozedurale Sequencer greifen nur, falls eine Datei fehlt.
const bgm={current:null,ready:{},failed:{},els:{}};
for(const name of ['menu','race']){const a=new Audio('assets/audio/'+name+'.mp3');a.loop=true;a.volume=.15;a.preload='auto';a.addEventListener('canplaythrough',()=>bgm.ready[name]=true);a.addEventListener('error',()=>bgm.failed[name]=true);bgm.els[name]=a;}
function stopBgm(){for(const a of Object.values(bgm.els))a.pause();bgm.current=null;}
function playBgm(name){if(!soundOn||bgm.failed[name])return;const a=bgm.els[name];if(bgm.current===name)return;stopBgm();const p=a.play();p.then(()=>{bgm.current=name;}).catch(()=>{if(bgm.current===name)bgm.current=null;});bgm.current=name;}
function note(freq,duration=.1,type='sine',volume=.06){if(!soundOn||!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+duration);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration);}
function setSound(){soundOn=!soundOn;if(soundOn)audioInit();if(engine)engine.gain.gain.value=soundOn?.014:0;if(!soundOn){stopBgm();try{speechSynthesis.cancel();}catch{}}else playBgm(state==='menu'||state==='finished'?'menu':'race');$('sound').textContent=soundOn?'♪ AN':'♪ AUS';$('sound').setAttribute('aria-label',soundOn?'Ton ausschalten':'Ton einschalten');}
function start(){keys.clear();buildCourse();state='countdown';elapsed=0;countdown=3;noticeTimer=0;beat=0;$('menu').hidden=true;$('result').hidden=true;$('hud').hidden=false;$('pause').hidden=false;$('touch').hidden=false;document.body.classList.add('racing');if(soundOn)audioInit();playBgm('race');say('Auf die Plätze — fertig — los!');updateCamera(1,true);}
function home(){state='menu';keys.clear();$('menu').hidden=false;$('hud').hidden=true;$('touch').hidden=true;$('pause').hidden=true;$('pausePanel').hidden=true;$('result').hidden=true;$('message').textContent='';document.body.classList.remove('racing');if(engine)engine.gain.gain.value=0;try{speechSynthesis.cancel();}catch{}playBgm('menu');}
let beforePause='race';function pause(){if(state==='paused'){state=beforePause;$('pausePanel').hidden=true;}else if(state==='race'||state==='countdown'){beforePause=state;state='paused';keys.clear();$('pausePanel').hidden=false;try{speechSynthesis.cancel();}catch{}}if(engine)engine.gain.gain.value=soundOn&&state==='race'?.014:0;}
function use(){if(state!=='race')return;const r=racers[0],result=activate(r,racers);if(!result)return;note(880,.2,'triangle');if(result.type==='banana'){const s=sample(r.distance-5,r.offset);const g=new T.Group();actors.add(g);g.position.copy(s.p);const b=mesh(new T.ConeGeometry(.6,1.3,5),gold,g,0,.7,0);b.rotation.z=.3;hazards.push({mesh:g,distance:r.distance-5,offset:r.offset,life:20});}if(result.type==='shell'&&result.target!==undefined){const target=racers[result.target];burst(target,0x8beb73,18);say('Volltreffer!');}if(result.type==='boost')say('Turbo!');notice({boost:'TURBO!',shield:'STERNENSCHILD',banana:'BANANE!',shell:'VOLL TREFFER!'}[result.type]);}
function burst(r,color,n=5){for(let i=0;i<n;i++){const g=mesh(new T.BoxGeometry(.15,.15,.15),new T.MeshBasicMaterial({color}),actors);g.position.copy(r.mesh.position);g.position.y+=.5;const a=Math.random()*TAU;sparks.push({mesh:g,v:new T.Vector3(Math.sin(a)*4,2+Math.random()*3,Math.cos(a)*4),life:.6});}}
function update(dt){if(state!=='race'&&state!=='countdown')return;if(state==='countdown'){const prev=Math.ceil(countdown);countdown-=dt;if(Math.ceil(countdown)!==prev)note(countdown>0?440:880,.16);$('message').textContent=countdown>0?String(Math.ceil(countdown)):'LOS!';if(countdown<=0){state='race';notice('LOS!',.8);}return;}
 elapsed+=dt;const player=racers[0];for(const r of racers){if(r.finishTime!==null)continue;const s=sample(r.distance),ahead=sample(r.distance+4);const cross=s.t.x*ahead.t.z-s.t.z*ahead.t.x;const input=r.id===0?{gas:autoGas||keys.has('ArrowUp')||keys.has('KeyW'),brake:keys.has('ArrowDown')||keys.has('KeyS'),steer:steering(),drift:keys.has('ShiftLeft')||keys.has('ShiftRight')}:{gas:true,steer:clamp(((Math.sin(r.distance*.013+r.id*1.8)*4)-r.offset)*.35,-1,1)};
 const oldLap=lap(r,length),oldBoost=r.boost;advance(r,dt,input,r.id===0?cross:0);if(r.id!==0){r.speed*=1-dt*(.025+r.id*.003);if(r.distance<player.distance-80)r.speed+=dt*2;if(r.cooldown===0&&r.item){activate(r,racers);r.cooldown=6;}}
 for(const fraction of [.18,.43,.72])if(Math.abs(((r.distance/length)%1+1)%1-fraction)*length<2&&Math.abs(r.offset)<7)r.boost=Math.max(r.boost,.9);
 if(r.id===0&&r.boost>oldBoost&&oldBoost===0){note(660,.12);if(r.drift===0)burst(r,0x7ceaff,8);}
 for(const b of boxes){const gap=Math.abs(((r.distance-b.distance)%length+length+length/2)%length-length/2);if(b.cooldown<=0&&!r.item&&gap<2.8&&Math.abs(r.offset-b.offset)<2){r.item=['boost','shell','banana','shield'][Math.floor(Math.random()*4)];b.cooldown=4;r.cooldown=4;if(r.id===0){note(1046,.15,'triangle');notice('ITEM GESAMMELT',.65);}}}
 if(r.id===0&&lap(r,length)>oldLap){const isLast=lap(r,length)===3;notice(isLast?'LETZTE RUNDE!':'RUNDE 2',1.5);say(isLast?'Letzte Runde!':'Runde zwei');note(880,.3);}
 finish(r,length,elapsed);syncKart(r,dt);if(r.boost>0&&frame%4===0)burst(r,0xffd452,1);if(r.id===0&&r.drift>.4&&frame%4===0)burst(r,r.drift>1.6?0xffb442:0x6addff,2);
 for(const h of hazards){if(r.id!==0&&h.life>0&&Math.abs(r.distance-h.distance)<3&&Math.abs(r.offset-h.offset)<1.8&&!r.shield){r.stun=2;r.speed*=.4;h.life=0;}}
 }
 for(let i=0;i<racers.length;i++)for(let j=i+1;j<racers.length;j++){const a=racers[i],b=racers[j];if(Math.abs(a.distance-b.distance)<2.4&&Math.abs(a.offset-b.offset)<1.6){const sign=a.offset>b.offset?1:-1;a.offset+=sign*dt*3;b.offset-=sign*dt*3;}}
 if(engine){engine.frequency.value=45+player.speed*1.8;engine.gain.gain.value=soundOn?.012:0;}
 // BGM: prozeduraler Chiptune-Sequencer (Melodie, Bass, Becken) — keine Assets, keine Lizenzkosten.
 const MEL=[523,0,659,0,784,659,880,784,698,0,587,0,523,587,659,0,523,0,659,0,784,880,1047,880,988,880,784,659,587,0,523,0],BAS=[131,0,196,0,131,0,196,0,175,0,220,0,175,0,220,0,131,0,196,0,131,0,196,0,147,0,196,0,147,0,123,0];
 if(bgm.failed.race&&soundOn&&Math.floor(elapsed*4.2)>beat){beat=Math.floor(elapsed*4.2);const i=beat%32;if(MEL[i])note(MEL[i],.14,'square',.016);if(BAS[i])note(BAS[i],.22,'triangle',.028);if(i%4===2)note(3000,.03,'square',.004);}
 if(player.finishTime!==null)end();}
function end(){elapsed=racers[0].finishTime??elapsed;state='finished';keys.clear();burst(racers[0],0xffd452,26);burst(racers[0],0xed6350,16);burst(racers[0],0x55bdb2,16);$('result').hidden=false;$('touch').hidden=true;const order=ranking(racers),place=order.indexOf(racers[0])+1;$('resultTitle').textContent=place===1?'Der Pokal gehört dir!':`Platz ${place}. Stark gefahren!`;$('resultTime').textContent=`${course.name} · 3 Runden · ${format(elapsed)}`;say(place===1?'Erster Platz! Der Pokal gehört dir!':`Platz ${place}. Stark gefahren!`);$('leaderboard').replaceChildren();for(let i=0;i<8;i++){const r=order[i],li=document.createElement('li');if(r.id===0)li.className='me';li.innerHTML=`<span>${i+1}.</span><span>${r.name}</span><span>${r.finishTime!==null?format(r.finishTime):'noch im Rennen'}</span>`;$('leaderboard').append(li);}if(engine)engine.gain.gain.value=0;try{if(new URLSearchParams(location.search).has('test'))return;const key='mushroom-rally-best-'+selected;const old=Number(localStorage.getItem(key)||Infinity);if(elapsed<old)localStorage.setItem(key,String(elapsed));}catch{}refreshBest();note(784,.4);$('message').textContent='';}
function format(time){return `${String(Math.floor(time/60)).padStart(2,'0')}:${(time%60).toFixed(1).padStart(4,'0')}`;}
function hud(){const p=racers[0];$('place').textContent=ranking(racers).indexOf(p)+1;$('lap').innerHTML=`${lap(p,length)} <em>/ 3</em>`;$('time').textContent=format(elapsed);$('speed').textContent=Math.round(p.speed*2.2);const icons={boost:'⚡',shell:'◉',banana:'🍌',shield:'★'},names={boost:'TURBO',shell:'SUCH-PANZER',banana:'BANANE',shield:'STERNENSCHILD'};$('itemIcon').textContent=icons[p.item]||'?';$('itemName').textContent=names[p.item]||'ITEM SAMMELN';$('driftbar').style.width=Math.min(100,p.drift/2.5*100)+'%';$('driftbar').style.background=p.drift>1.6?'#ffcb55':'#73dcff';$('driftlabel').textContent=p.boost>0?'TURBO AKTIV!':p.drift>.7?'LOS LASSEN → MINI-TURBO':coarseInput?'DRIFT-TASTE HALTEN':'SHIFT HALTEN · DRIFT';}
function refreshBest(){try{document.querySelectorAll('#tracks .track').forEach((b,i)=>{const t=localStorage.getItem('mushroom-rally-best-'+i);let span=b.querySelector('.best');if(!span){span=document.createElement('span');span.className='best';b.append(span);}span.textContent=t?'BEST '+format(Number(t)):'—';});}catch{}}
function drawMap(){const c=$('map'),q=c.getContext('2d');q.clearRect(0,0,200,160);q.lineWidth=9;q.lineJoin='round';q.strokeStyle='#23483988';q.beginPath();for(let i=0;i<=120;i++){const p=sample(length*i/120).p;const x=100+p.x*.66,y=80+p.z*.66;i?q.lineTo(x,y):q.moveTo(x,y);}q.stroke();q.lineWidth=3;q.strokeStyle='#fff6dd';q.stroke();for(const r of [...racers].reverse()){const p=sample(r.distance,r.offset).p;q.fillStyle=r.id===0?'#ffe16a':'#fff';q.beginPath();q.arc(100+p.x*.66,80+p.z*.66,r.id===0?4.5:2.7,0,TAU);q.fill();}}
const tempLook=new T.Vector3();function updateCamera(dt,snap=false){if(state==='menu'){const s=sample(length*.05);const angle=.45+Math.sin(performance.now()*.00006)*.16;camera.position.set(s.p.x+Math.sin(angle)*48,30,s.p.z+Math.cos(angle)*42);camera.lookAt(s.p.x-12,1,s.p.z-10);return;}const p=racers[0],s=sample(p.distance,p.offset),future=sample(p.distance+12,p.offset*.5);const desired=s.p.clone().addScaledVector(s.t,-10.7);desired.y=5.9;camera.position.lerp(desired,snap?1:1-Math.exp(-dt*7));tempLook.copy(future.p);tempLook.y=1.3;camera.lookAt(tempLook);if(p.boost>0){camera.position.y+=Math.sin(elapsed*63)*.07;camera.position.x+=Math.sin(elapsed*49)*.05;}camera.fov=58+(p.boost>0?9:0);camera.updateProjectionMatrix();}
// Adaptive Qualität: alle 2 s FPS messen; unter 45 FPS stufenweise Pixel-Ratio senken, zuletzt Schatten aus.
function adaptQuality(fps){if(state!=='race'||fps>=45||quality.level>=2)return;quality.level++;quality.dprCap=Math.max(quality.level===1?1:.85,quality.dprCap-.35);if(quality.level===2){renderer.shadowMap.enabled=false;sun.castShadow=false;scene.traverse(o=>{if(o.isMesh)for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m)m.needsUpdate=true;});}renderer.setPixelRatio(Math.min(devicePixelRatio,quality.dprCap));resize();}
function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000||.016,.05);last=now;frame++;quality.fpsFrames++;if(quality.fpsStart&&now-quality.fpsStart>2000){adaptQuality(quality.fpsFrames*1000/(now-quality.fpsStart));quality.fpsFrames=0;quality.fpsStart=now;}else if(!quality.fpsStart)quality.fpsStart=now;if(state==='menu'&&bgm.failed.menu&&soundOn&&Math.floor(now/430)>menuBeat){menuBeat=Math.floor(now/430);note([262,330,392,523][menuBeat%4],.5,'sine',.011);if(menuBeat%8===0)note(131,.9,'sine',.014);}if(state!=='paused'){update(dt);for(const b of boxes){b.cooldown=Math.max(0,b.cooldown-dt);b.mesh.visible=b.cooldown<=0;b.mesh.rotation.y=now*.001;b.mesh.position.y=1.65+Math.sin(now*.003+b.distance)*.2;}for(let i=sparks.length-1;i>=0;i--){const p=sparks[i];p.life-=dt;p.v.y-=dt*8;p.mesh.position.addScaledVector(p.v,dt);p.mesh.scale.setScalar(Math.max(0,p.life*1.6));if(p.life<=0){actors.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose();sparks.splice(i,1);}}for(const f of flags){const pos=f.mesh.geometry.attributes.position,q=pos.array;for(let v=0;v<pos.count;v++){const xn=(f.base[v*3]+.75)/1.5;q[v*3+2]=f.base[v*3+2]+Math.sin(elapsed*6+xn*4)*.11*xn;}pos.needsUpdate=true;}for(let i=hazards.length-1;i>=0;i--){hazards[i].life-=dt;if(hazards[i].life<=0){actors.remove(hazards[i].mesh);hazards.splice(i,1);}}if(noticeTimer>0){noticeTimer-=dt;if(noticeTimer<=0&&state!=='countdown')$('message').textContent='';}updateCamera(dt);}if(frame%3===0){hud();drawMap();}renderer.render(scene,camera);}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);
for(let i=0;i<4;i++){const b=document.createElement('button');b.className='swatch'+(i===0?' selected':'');b.style.setProperty('--swatch','#'+colors[i].toString(16));b.setAttribute('aria-label',driverNames[i]);b.setAttribute('aria-pressed',String(i===0));b.onclick=()=>{colorIndex=i;$('colors').querySelectorAll('button').forEach((x,j)=>{x.classList.toggle('selected',i===j);x.setAttribute('aria-pressed',String(i===j));});$('driverName').textContent=driverNames[i];buildCourse();};$('colors').append(b);}
courses.forEach((c,i)=>{const b=document.createElement('button');b.className='track'+(i===0?' selected':'');b.innerHTML=`<i>${c.icon}</i><b>${c.name}</b><span>${i===0?'Klassisch':i===1?'Schnell':'Knifflig'}</span>`;b.setAttribute('aria-pressed',String(i===0));b.onclick=()=>{selected=i;$('tracks').querySelectorAll('button').forEach((x,j)=>{x.classList.toggle('selected',i===j);x.setAttribute('aria-pressed',String(i===j));});buildCourse();};$('tracks').append(b);});
refreshBest();
$('start').onclick=start;$('again').onclick=start;$('home').onclick=home;$('quit').onclick=home;$('pause').onclick=pause;$('resume').onclick=pause;$('sound').onclick=setSound;$('item').onclick=use;$('full').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>{});};
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(!e.repeat){if(e.code==='Space')use();if(e.code==='Escape'||e.code==='KeyP')pause();if(e.code==='KeyR'&&state==='race'){racers[0].offset=0;racers[0].speed=12;}if(e.code==='Enter'&&state==='menu')start();}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();if(state==='race'||state==='countdown')pause();});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys.delete(b.dataset.key);});
// GLB-Prototypen laden (4s Timeout), danach starten; bei Fehler prozeduraler Fallback.
Promise.race([Promise.all([loadProto('assets/kart.glb'),loadProto('assets/mushroom.glb'),loadProto('assets/gate.glb'),loadProto('assets/tree.glb')]),new Promise(r=>setTimeout(r,4000))]).then(([k,p,g,t])=>{kartProto=k;pilzProto=p;gateProto=g;treeProto=t;}).catch(()=>{}).finally(()=>{buildCourse();resize();playBgm('menu');requestAnimationFrame(loop);});
// Explicit test interface available only with ?test=1; no production autoplay.
if(new URLSearchParams(location.search).has('test'))window.rallyTest={start,step:(seconds,input={gas:true})=>{for(let i=0;i<seconds*60;i++){advance(racers[0],1/60,input);elapsed+=1/60;if(finish(racers[0],length,elapsed))break;}if(racers[0].finishTime!==null)end();},state:()=>({state,length,racers:racers.map(({mesh,...r})=>r)}),setItem:item=>racers[0].item=item,use,pause,home,perf:()=>({drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,dpr:renderer.getPixelRatio(),qualityLevel:quality.level}),bgm:()=>({ready:bgm.ready,failed:bgm.failed,playing:bgm.current})};

const autoButton=document.createElement('button');autoButton.id='autoGas';autoButton.textContent='Auto-Gas: AUS';autoButton.setAttribute('aria-pressed','false');autoButton.onclick=()=>{autoGas=!autoGas;autoButton.textContent='Auto-Gas: '+(autoGas?'AN':'AUS');autoButton.setAttribute('aria-pressed',String(autoGas));};document.querySelector('.controls').after(autoButton);
if(new URLSearchParams(location.search).has('test')){
 const panel=document.createElement('aside');panel.id='testPanel';panel.style.cssText='position:fixed;bottom:0;left:35%;z-index:30;background:#111;padding:10px;display:flex;gap:8px';
 for(const [text,action] of [['Test: Turbo',()=>{window.rallyTest.setItem('boost');state='race';use();}],['Test: Ziel',()=>{state='race';window.rallyTest.step(length*3/50+20);}],['Test: Status',()=>{const st=window.rallyTest.state();panel.dataset.state=st.state;}]]){const b=document.createElement('button');b.textContent=text;b.style.cssText='color:#fff;background:#345;padding:10px';b.onclick=action;panel.append(b);}document.body.append(panel);
}